# Generated by Django 2.0 on 2020-04-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='f_name',
            field=models.CharField(max_length=200, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], default='H', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='l_name',
            field=models.CharField(max_length=200, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='n_documento',
            field=models.CharField(max_length=14, verbose_name='Numero de documento'),
        ),
    ]
