# Generated by Django 2.0 on 2020-04-16 04:44

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200416_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre'), ('O', 'Otro')], default='H', max_length=200, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='height',
            field=models.IntegerField(verbose_name='Estatura en Centimetros'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Numero telefonico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='skype',
            field=models.CharField(max_length=200, verbose_name='Skype ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='weight',
            field=models.IntegerField(verbose_name='Peso en Kilogramos'),
        ),
    ]
