# Generated by Django 2.0 on 2020-04-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200416_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='city',
            field=models.CharField(choices=[('Aguachica', 'Aguachica'), ('Apartadó', 'Apartadó'), ('Arauca', 'Arauca'), ('Armenia', 'Armenia'), ('Barrancabermeja', 'Barrancabermeja'), ('Barranquilla', 'Barranquilla'), ('Bello', 'Bello'), ('Bogotá', 'Bogotá'), ('Bucaramanga', 'Bucaramanga'), ('Buenaventura', 'Buenaventura'), ('Buga', 'Buga'), ('Cali', 'Cali'), ('Cartago', 'Cartago'), ('Cartagena', 'Cartagena'), ('Caucasia', 'Caucasia'), ('Cereté', 'Cereté'), ('Chia', 'Chia'), ('Ciénaga', 'Ciénaga'), ('Cúcuta', 'Cúcuta'), ('Dosquebradas', 'Dosquebradas'), ('Duitama', 'Duitama'), ('Envigado', 'Envigado'), ('Facatativá', 'Facatativá'), ('Florencia', 'Florencia'), ('Floridablanca', 'Floridablanca'), ('Fusagasugá', 'Fusagasugá'), ('Girardot', 'Girardot'), ('Girón', 'Girón'), ('Ibagué', 'Ibagué'), ('Ipiales', 'Ipiales'), ('Itagüí', 'Itagüí'), ('Jamundí', 'Jamundí'), ('Lorica', 'Lorica'), ('Los Patios', 'Los Patios'), ('Magangué', 'Magangué'), ('Maicao', 'Maicao'), ('Malambo', 'Malambo'), ('Medellín', 'Medellín'), ('Manizales', 'Manizales'), ('Melgar', 'Melgar'), ('Montería', 'Montería'), ('Neiva', 'Neiva'), ('Ocaña', 'Ocaña'), ('Paipa', 'Paipa'), ('Palmira', 'Palmira'), ('Pamplona', 'Pamplona'), ('Pasto', 'Pasto'), ('Pereira', 'Pereira'), ('Piedecuesta', 'Piedecuesta'), ('Pitalito', 'Pitalito'), ('Popayán', 'Popayán'), ('Quibdó', 'Quibdó'), ('Riohacha', 'Riohacha'), ('Rionegro', 'Rionegro'), ('Sabanalarga', 'Sabanalarga'), ('Sahagún', 'Sahagún'), ('San Andrés Isla', 'San Andrés Isla'), ('Santa Marta', 'Santa Marta'), ('Sincelejo', 'Sincelejo'), ('Soacha', 'Soacha'), ('Sogamoso', 'Sogamoso'), ('Soledad', 'Soledad'), ('Tibú', 'Tibú'), ('Tuluá', 'Tuluá'), ('Tumaco', 'Tumaco'), ('Tunja', 'Tunja'), ('Turbo', 'Turbo'), ('Valledupar', 'Valledupar'), ('Villa de leyva', 'Villa de leyva'), ('Villa del Rosario', 'Villa del Rosario'), ('Villavicencio', 'Villavicencio'), ('Yopal', 'Yopal'), ('Yumbo', 'Yumbo'), ('Zipaquirá', 'Zipaquirá')], default='Zipaquirá', max_length=200, verbose_name='Ciudades'),
        ),
    ]
