# Generated by Django 2.0 on 2020-04-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiebre', models.BooleanField()),
                ('tos', models.BooleanField()),
                ('moco', models.BooleanField()),
                ('congestion', models.BooleanField()),
                ('estornudos', models.BooleanField()),
                ('d_garganta', models.BooleanField()),
                ('m_garganta', models.BooleanField()),
                ('d_respirar', models.BooleanField()),
                ('flema', models.BooleanField()),
                ('vomito', models.BooleanField()),
                ('diarrea', models.BooleanField()),
                ('cansancio', models.BooleanField()),
                ('quebrahueso', models.BooleanField()),
                ('x_ray', models.BooleanField()),
            ],
        ),
    ]
