# Generated by Django 2.0 on 2020-04-16 14:51

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sintomas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('l_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('n_documento', models.CharField(max_length=14, verbose_name='Numero de documento')),
                ('address', models.CharField(max_length=200, verbose_name='Direccion')),
                ('city', models.CharField(choices=[('Aguachica', 'Aguachica'), ('Apartadó', 'Apartadó'), ('Arauca', 'Arauca'), ('Armenia', 'Armenia'), ('Barrancabermeja', 'Barrancabermeja'), ('Barranquilla', 'Barranquilla'), ('Bello', 'Bello'), ('Bogotá', 'Bogotá'), ('Bucaramanga', 'Bucaramanga'), ('Buenaventura', 'Buenaventura'), ('Buga', 'Buga'), ('Cali', 'Cali'), ('Cartago', 'Cartago'), ('Cartagena', 'Cartagena'), ('Caucasia', 'Caucasia'), ('Cereté', 'Cereté'), ('Chia', 'Chia'), ('Ciénaga', 'Ciénaga'), ('Cúcuta', 'Cúcuta'), ('Dosquebradas', 'Dosquebradas'), ('Duitama', 'Duitama'), ('Envigado', 'Envigado'), ('Facatativá', 'Facatativá'), ('Florencia', 'Florencia'), ('Floridablanca', 'Floridablanca'), ('Fusagasugá', 'Fusagasugá'), ('Girardot', 'Girardot'), ('Girón', 'Girón'), ('Ibagué', 'Ibagué'), ('Ipiales', 'Ipiales'), ('Itagüí', 'Itagüí'), ('Jamundí', 'Jamundí'), ('Lorica', 'Lorica'), ('Los Patios', 'Los Patios'), ('Magangué', 'Magangué'), ('Maicao', 'Maicao'), ('Malambo', 'Malambo'), ('Medellín', 'Medellín'), ('Manizales', 'Manizales'), ('Melgar', 'Melgar'), ('Montería', 'Montería'), ('Neiva', 'Neiva'), ('Ocaña', 'Ocaña'), ('Paipa', 'Paipa'), ('Palmira', 'Palmira'), ('Pamplona', 'Pamplona'), ('Pasto', 'Pasto'), ('Pereira', 'Pereira'), ('Piedecuesta', 'Piedecuesta'), ('Pitalito', 'Pitalito'), ('Popayán', 'Popayán'), ('Quibdó', 'Quibdó'), ('Riohacha', 'Riohacha'), ('Rionegro', 'Rionegro'), ('Sabanalarga', 'Sabanalarga'), ('Sahagún', 'Sahagún'), ('San Andrés Isla', 'San Andrés Isla'), ('Santa Marta', 'Santa Marta'), ('Sincelejo', 'Sincelejo'), ('Soacha', 'Soacha'), ('Sogamoso', 'Sogamoso'), ('Soledad', 'Soledad'), ('Tibú', 'Tibú'), ('Tuluá', 'Tuluá'), ('Tumaco', 'Tumaco'), ('Tunja', 'Tunja'), ('Turbo', 'Turbo'), ('Valledupar', 'Valledupar'), ('Villa de leyva', 'Villa de leyva'), ('Villa del Rosario', 'Villa del Rosario'), ('Villavicencio', 'Villavicencio'), ('Yopal', 'Yopal'), ('Yumbo', 'Yumbo'), ('Zipaquirá', 'Zipaquirá')], default='Zipaquirá', max_length=200, verbose_name='Ciudades')),
                ('departamento', models.CharField(choices=[('Amazonas', 'Amazonas'), ('Antioquia', 'Antioquia'), ('Arauca', 'Arauca'), ('Atlántico', 'Atlántico'), ('Bolívar', 'Bolívar'), ('Boyacá', 'Boyacá'), ('Bogotá DC', 'Bogotá DC'), ('Caldas', 'Caldas'), ('Caquetá', 'Caquetá'), ('Casanare', 'Casanare'), ('Cauca', 'Cauca'), ('Cesar', 'Cesar'), ('Chocó', 'Chocó'), ('Córdoba', 'Córdoba'), ('Cundinamarca', 'Cundinamarca'), ('Guainía', 'Guainía'), ('Guaviare', 'Guaviare'), ('Huila', 'Huila'), ('La Guajira', 'La Guajira'), ('Magdalena', 'Magdalena '), ('Meta', 'Meta'), ('Nariño', 'Nariño'), ('Norte de Santander', 'Norte de Santander'), ('Putumayo', 'Putumayo'), ('Quindío', 'Quindío'), ('Risaralda', 'Risaralda'), ('San Andrés y Providencia', 'San Andrés y Providencia'), ('Santander', 'Santander'), ('Sucre', 'Sucre'), ('Tolima', 'Tolima'), ('Valle del Cauca', 'Valle del Cauca'), ('Vaupés', 'Vaupés'), ('Vichada', 'Vichada')], default='Vichada', max_length=200)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('phone', models.CharField(max_length=200, verbose_name='Numero telefonico')),
                ('skype', models.CharField(max_length=200, verbose_name='Skype ID')),
                ('gender', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre'), ('O', 'Otro')], default='H', max_length=200, verbose_name='Genero')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('weight', models.IntegerField(verbose_name='Peso en Kilogramos')),
                ('height', models.IntegerField(verbose_name='Estatura en Centimetros')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
            ],
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='cansancio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='congestion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='d_garganta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='d_respirar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='diarrea',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='estornudos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='fiebre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='flema',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='m_garganta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='quebrahueso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='tos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='vomito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='x_ray',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sintomas',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sintomas.Paciente'),
        ),
    ]
