# Generated by Django 2.0 on 2020-04-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sintomas', '0004_paciente_sintomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintomas',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sintomas.Paciente'),
        ),
    ]
