# Generated by Django 2.0 on 2020-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sintomas', '0005_auto_20200416_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintomas',
            name='test',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='gender',
            field=models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Otro', 'Otro')], default='Hombre', max_length=200, verbose_name='Genero'),
        ),
    ]
