# Generated by Django 2.0 on 2020-04-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sintomas', '0008_paciente_sintomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintomas',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sintomas.Paciente'),
        ),
    ]
