# Generated by Django 2.0 on 2020-04-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sintomas', '0009_auto_20200416_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sintomas',
            name='test',
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='cansancio',
            field=models.BooleanField(default=False, verbose_name='¿Tiene cansancio?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='congestion',
            field=models.BooleanField(default=False, verbose_name='¿Tiene congestión nasal?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='d_garganta',
            field=models.BooleanField(default=False, verbose_name='¿Tiene dolor de garganta?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='d_respirar',
            field=models.BooleanField(default=False, verbose_name='¿Tiene dificultad para respirar?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='diarrea',
            field=models.BooleanField(default=False, verbose_name='¿Tiene diarrea?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='estornudos',
            field=models.BooleanField(default=False, verbose_name='¿Tiene estornudos?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='fiebre',
            field=models.BooleanField(default=False, verbose_name='¿Tiene fiebre?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='flema',
            field=models.BooleanField(default=False, verbose_name='¿Tiene flema?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='m_garganta',
            field=models.BooleanField(default=False, verbose_name='¿Tiene malestar de garganta?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='moco',
            field=models.BooleanField(default=False, verbose_name='¿Tiene moco?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='quebrahueso',
            field=models.BooleanField(default=False, verbose_name='¿Tiene quebrahueso?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='tos',
            field=models.BooleanField(default=False, verbose_name='¿Tiene tos?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='vomito',
            field=models.BooleanField(default=False, verbose_name='¿Tiene vómito?'),
        ),
        migrations.AlterField(
            model_name='sintomas',
            name='x_ray',
            field=models.BooleanField(default=False, verbose_name='¿Tiene mancha en el pulmón?'),
        ),
    ]
